// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7nbk8xJCVa_cTbUzC-HbCcm1d8oumQ8Y',
    appId: '1:991273087376:web:2ca3bc08066fac22efc315',
    messagingSenderId: '991273087376',
    projectId: 'food-delivery-v2-6016f',
    authDomain: 'food-delivery-v2-6016f.firebaseapp.com',
    databaseURL: 'https://food-delivery-v2-6016f-default-rtdb.firebaseio.com',
    storageBucket: 'food-delivery-v2-6016f.appspot.com',
    measurementId: 'G-523HFY572R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7WsS847KB8haI9zqWgUjKU2SusmBvTv4',
    appId: '1:991273087376:android:81d8083eae787151efc315',
    messagingSenderId: '991273087376',
    projectId: 'food-delivery-v2-6016f',
    databaseURL: 'https://food-delivery-v2-6016f-default-rtdb.firebaseio.com',
    storageBucket: 'food-delivery-v2-6016f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSY_MYALpCIgRjXoFX4js3zfkP1Quy64Y',
    appId: '1:991273087376:ios:567d5a8f63565897efc315',
    messagingSenderId: '991273087376',
    projectId: 'food-delivery-v2-6016f',
    databaseURL: 'https://food-delivery-v2-6016f-default-rtdb.firebaseio.com',
    storageBucket: 'food-delivery-v2-6016f.appspot.com',
    iosClientId: '991273087376-7o1fkko2o8521f5sto0t5bkch9ah271l.apps.googleusercontent.com',
    iosBundleId: 'com.example.floweresApp',
  );
}
